### ISSUE TITLE
Что осталось доделать.

### ISSUE THREAD

**Issue by levs2001** [levs2001/lr-game-shop#4]
Замечания от преподавателя:
* Добавить в отчет архитектуру (картинку взаимодействия кластеров и api)
* CRUD запросы можно не мерить по времени. Главное, чтобы было удобное api.
* Можно использовать S3 для картинок вместо графовой, но обосновать почему мы хотим S3, а не кладем картинки в cassandra, сравнить с закладкой картинок в кассандру. Либо можно куда-то впихнуть графовую, либо поиграться с Tarantool.

**Comment by RSLN3** [comment]
Общий работающий клиент без картинок. - Лев (дедлайн 9.04).
s3 с картинками, как передавать картинки. -Руслан (дедлайн 9.04).
Сгенирить данные 2млн (регионозависимые поля на 3х языках). -Руслан (дедлайн 9.04).
Формат одного ряда данных
```
{
game_id: 1245
developer: superdeveloper
publisher: p1
release_date: 23.04.34
genre: anime game
platform: xbox
rating: 7.0
country_fields:
    [
        {
            language_code: ru
            title
            description
            price
        },
        {
            language_code: en
            title
            description
            price
        },
        {
            language_code: fr
            title
            description
            price
        },
    ]
}
```

Соединить s3 и клиент.
Залить данные.
Тест отключения кластера.
UI для Rest API.
