### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by RSLN3** [levs2001/lr-game-shop#5]
Добавлять игру/игры 
POST(поля которые есть в схеме для всех языков) картинка потом???
Формат записи (пример):
```
{
game_id: 1245
developer: superdeveloper
publisher: p1
release_date: 23.04.34
genre: anime game
platform: xbox
rating: 7.0
country_fields:
    [
        {
            language_code: RU
            title
            description
            price
        },
        {
            language_code: EN
            title
            description
            price
        },
        {
            language_code: FR
            title
            description
            price
        },
    ]
}
```

Получать игру/игры 
GET(id)
GET(title + limit)
GET(developer + limit)
GET(publisher + limit)

Редактировать игру/игры.
UPDATE(id + language_code, все поля)    

Удалять игру/игры.
DELETE(id + language_code)

**Comment by levs2001** [comment]
TODO:
Чтобы поиск (GET с лимитом) не втупил нужно:
* Добавить в монго индексы по developer и publisher
* Добавить в кассандру индекс по title
